# Generated by Django 5.2.5 on 2025-08-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
